name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd backend && npm ci
        cd ../frontend && npm ci
        cd ../mcp-modules && npm ci
    
    - name: Lint backend
      run: cd backend && npm run lint --if-present
    
    - name: Lint frontend  
      run: cd frontend && npm run lint --if-present
    
    - name: TypeScript check backend
      run: cd backend && npx tsc --noEmit
    
    - name: TypeScript check frontend
      run: cd frontend && npx tsc --noEmit
    
    - name: TypeScript check mcp-modules
      run: cd mcp-modules && npx tsc --noEmit
    
    - name: Run backend tests
      run: cd backend && npm test --if-present
    
    - name: Run frontend tests
      run: cd frontend && npm test --if-present
    
    - name: Build backend
      run: cd backend && npm run build --if-present
    
    - name: Build frontend
      run: cd frontend && npm run build
    
    - name: Build mcp-modules
      run: cd mcp-modules && npm run build --if-present

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd backend && npm ci
        cd ../frontend && npm ci
    
    - name: Run npm audit (backend)
      run: cd backend && npm audit --audit-level moderate
    
    - name: Run npm audit (frontend)
      run: cd frontend && npm audit --audit-level moderate
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  build-and-sbom:
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd backend && npm ci
        cd ../frontend && npm ci
    
    - name: Build production
      run: |
        cd frontend && npm run build
        cd ../backend && npm run build --if-present
    
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        output-file: ./sbom.spdx.json
    
    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: ./sbom.spdx.json